spring:
  application:
    name: service-provider
  main:
    allow-bean-definition-overriding: true
server:
  port: 9999

dubbo:
  scan:
    base-packages: com.seven.provider
  protocol:
    id: dubbo
    name: dubbo
    port: 20882
  registry:
    id: dubboRegistry
    timeout: 5000
    address: zookeeper://127.0.0.1:2181
    client: curator
  metadata-report:
    address: zookeeper://127.0.0.1:2181